version: '2'
volumes:
  nrese2e:
services:
  NRESCeleryRabbitmq:
    image: rabbitmq:3-management
    ports:
    - 15673:15672/tcp
    labels:
      io.rancher.container.pull_image: always
    logging:
      options:
        max-size: '100m'
        max-file: '3'
  NRESPipelineTestFitsExchange:
    image: rabbitmq:3-management
    ports:
    - 15674:15672/tcp
    labels:
      io.rancher.container.pull_image: always
    logging:
      options:
        max-size: '100m'
        max-file: '3'
  NRESPipelineE2EData:
    image: docker.lco.global/nres-pipeline-e2e-data:1.0.1
    entrypoint:
    - /bin/true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
    volumes:
    - nrese2e:/archive
    logging:
      options:
        max-size: '100m'
        max-file: '3'
  NRESPipelineTest:
    image: ${DOCKER_IMG}
    environment:
      BOSUN_HOSTNAME: alertsdev.lco.gtn
      BROKER_PASSWORD: ${RABBIT_PASSWORD}
      BROKER_URL: amqp://${RABBITMQ_USER}:${RABBIT_PASSWORD}@nresceleryrabbitmq:5672/
      BROKER_USERNAME: ${RABBITMQ_USER}
      DB_URL: sqlite:////archive/engineering/test.db
      FITS_BROKER: amqp://${RABBITMQ_USER}:${RABBIT_PASSWORD}@nrestestfitsexchange:5672/
      NRES_DATA_ROOT: /archive/engineering/
      RABBITMQ_HOST: nresceleryrabbitmq
      OPENTSDB_PYTHON_METRICS_TEST_MODE: 'False'
    volumes_from:
    - NRESPipelineE2EData
    links:
    - NRESCeleryRabbitmq:nresceleryrabbitmq
    - NRESPipelineTestFitsExchange:nrestestfitsexchange
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: NRESPipelineE2EData,NRESPipelineTestFitsExchange,NRESCeleryRabbitmq
    logging:
      options:
        max-size: '100m'
        max-file: '3'
