version: '2'
services:
  NRESCeleryRabbitmq:
    image: rabbitmq:3-management
    ports:
    - 15673:15672/tcp
    labels:
      io.rancher.container.pull_image: always
  NRESPipelineTestFitsExchange:
    image: rabbitmq:3-management
    ports:
    - 15674:15672/tcp
    labels:
      io.rancher.container.pull_image: always
  NRESPipelineE2EData:
    image: docker.lco.global/nres-pipeline-e2e-data:1.0.0
    entrypoint:
    - /bin/true
    volumes:
    - nrese2e:/archive
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
  NRESPipelineTest:
    image: ${DOCKER_IMG}
    environment:
      BOSUN_HOSTNAME: alertsdev.lco.gtn
      BROKER_PASSWORD: guest
      BROKER_URL: amqp://guest:guest@nresceleryrabbitmq:5672/
      BROKER_USERNAME: guest
      DB_URL: sqlite:////archive/engineering/test.db
      FITS_BROKER: amqp://guest:guest@nrestestfitsexchange:5672/
      NRES_DATA_ROOT: /archive/engineering/
      RABBITMQ_HOST: nresceleryrabbitmq
      OPENTSDB_PYTHON_METRICS_TEST_MODE: 'False'
    volumes_from:
    - NRESPipelineE2EData
    links:
    - NRESCeleryRabbitmq:nresceleryrabbitmq
    - NRESPipelineTestFitsExchange:nrestestfitsexchange
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: NRESPipelineE2EData,NRESPipelineTestFitsExchange,NRESCeleryRabbitmq
