import os.path

def stds_rm(indx):

    """

    Reads the standards.csv file, deletes all of the lines identified in the
    index array indx (presumably generated by a "where" statement), and
    writes the result back out to standards.csv

    Run this first to set path if needed:
    import os.path
    os.environ["NRESROOT"] = "/Users/rolfsmei/Documents/research/nres_4/nres_copy4/"

    """

    import pandas as pd

    nresroot=os.getenv("NRESROOT")

    stdsfile = nresroot+'reduced/csv/standards.csv'

    #Read in stdsfilefile
    df = pd.read_csv(stdsfile)

    #Dropping Filenames matching lines in indx
    df_out = df[~df['Filename'].isin(indx)]

    #Writing out file
    df_out.to_csv(stdsfile,index=False)