import os.path

def zeros_rm(indx):

    """

    Reads the zeros.csv file, deletes all of the lines identified in the
    index array indx (presumably generated by a "where" statement), and
    writes the result back out to zeros.csv

    Run this first to set path if needed:
    import os.path
    os.environ["NRESROOT"] = "/Users/rolfsmei/Documents/research/nres_4/nres_copy4/"

    Can create test list like this:
    indx=['zero/ZERO2015174.5243.fits','zero/ZERO2015176.5243.fits']

    """

    import pandas as pd

    nresroot=os.getenv("NRESROOT")

    zerofile = nresroot+'reduced/csv/zeros.csv'

    #Read in zerofile
    df = pd.read_csv(zerofile)

    #Dropping Filenames matching lines in indx
    df_out = df[~df['Filename'].isin(indx)]

    #Writing out file
    df_out.to_csv(zerofile,index=False)